package com.roch.hzz_baidumap_demo.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.roch.hzz_baidumap_demo.entity.LatLonEntity;
import com.roch.hzz_baidumap_demo.entity.Message;

import com.roch.hzz_baidumap_demo.entity.LatLonEntityDao;
import com.roch.hzz_baidumap_demo.entity.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig latLonEntityDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final LatLonEntityDao latLonEntityDao;
    private final MessageDao messageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        latLonEntityDaoConfig = daoConfigMap.get(LatLonEntityDao.class).clone();
        latLonEntityDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        latLonEntityDao = new LatLonEntityDao(latLonEntityDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(LatLonEntity.class, latLonEntityDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        latLonEntityDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public LatLonEntityDao getLatLonEntityDao() {
        return latLonEntityDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
